config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  root to: 'pages#index'

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end

  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
  end

  resources :posts do
    collection do
      get 'hobby'
      get 'study'
      get 'team'
    end
  end

  namespace :private do
    resources :conversations, only: [:create] do
      member do
        post :close
        post :open
        get :open
        get :close
      end
    end
    resources :messages, only: [:index, :create]
  end

  resources :contacts, only: [:create, :update, :destroy]

  namespace :group do
    resources :conversations do
      member do
        post :close
        post :open
      end
    end
    resources :messages, only: [:index, :create]
  end


  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/helpers/navigation_helper.rb
module NavigationHelper
  def collapsible_links_partial_path
    if user_signed_in?
      "layouts/navigation/collapsible_elements/signed_in_links"
    else
      "layouts/navigation/collapsible_elements/non_signed_in_links"
    end
  end

  def nav_header_content_partials
    partials = []
    if params[:controller] == "messengers"
      partials << "layouts/navigation/header/messenger_header"
    else # controller is not messengers
      partials << "layouts/navigation/header/toggle_button"
      partials << "layouts/navigation/header/home_button"
      partials << "layouts/navigation/header/dropdowns" if user_signed_in?
    end
    partials
  end

  # return a conversation header partial's path
  def conversation_header_partial_path(conversation)
    if conversation.class == Private::Conversation
      'layouts/navigation/header/dropdowns/conversations/private_conversation'
    else
      'layouts/navigation/header/dropdowns/conversations/group_conversation'
    end
  end

end

app/views/layouts/navigation/collapsible_elements/_non_signed_in_links.html.erb
<li class="nav-item"><%= link_to 'Login', login_path, class: 'nav-link' %></li>
<li class="nav-item"><%= link_to 'Signup', signup_path, class: 'nav-link' %></li>

app/views/layouts/navigation/collapsible_elements/_signed_in_links.html.erb
<li class="nav-item dropdown pc-menu">
  <a id="user-settings" class="nav-link dropdown-toggle"
     data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">
    <span id="user-name"><%= current_user.name %></span>
  </a>
  <ul class="dropdown-menu">
    <li><%= link_to 'Edit Profile', edit_user_registration_path, class: 'dropdown-item' %></li>
    <li><%= link_to 'Log out', destroy_user_session_path, data: { turbo_method: :delete }, class: 'dropdown-item' %></li>
  </ul>
</li>

<li class="nav-item mobile-menu">
  <%= link_to 'Edit Profile', edit_user_registration_path, class: 'nav-link' %>
</li>
<li class="nav-item mobile-menu">
  <%= link_to 'Log out', destroy_user_session_path, data: { turbo_method: :delete }, class: 'nav-link' %>
</li>